### ISSUE TITLE
 Password problem.

### ISSUE THREAD

**Issue by archtrorg** [zurg3/arch-linux-info#1]
I tried it on virtualbox. There is a problem in the root and user password section. The password should not appear on the screen. It doesn't accept my preferred password. You must correct this problem. Thank you for your work.   @cumali

**Comment by zurg3** [comment]
I know that the passwords appear while user is typing them and this is such a security problem. But the script is basically intended for my needs, so this is not a big problem for me.

As it's written in README.md:
> If installation script doesn't meet your requirements, you can fork this repository to edit the script to your needs.

**Comment by archtrorg** [comment]
Ok, thank you.
